import Foundation

public struct DefaultBuiltInPhoneToolSeedFactory: BuiltInPhoneToolSeeding {
    public init() {}

    public var tools: [BuiltInPhoneToolDefinition] {
        Self.defaultTools
    }

    public static let defaultTools: [BuiltInPhoneToolDefinition] = [
        BuiltInPhoneToolDefinition(
            id: .memorySave,
            displayName: KairoL10n.string("chat.action.displayName.saveMemory"),
            category: .memory,
            schema: BuiltInPhoneToolSchema(input: "MemoryRecordDraft", output: "MemoryRecord"),
            permissionRequirement: .none,
            availabilityStatus: .available,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.memory", executor: "SandboxActionExecutor.saveMemory"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.memory]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Memory store unavailable.", safeAlternative: "Keep the content in chat without saving it."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.saveMemory], shortcutNodeKinds: [.saveMemory], recipeStepKinds: [.saveMemory])
        ),
        BuiltInPhoneToolDefinition(
            id: .memorySearch,
            displayName: KairoL10n.string("memory.search.section"),
            category: .memory,
            schema: BuiltInPhoneToolSchema(input: "MemorySearchQuery", output: "MemorySearchResults"),
            permissionRequirement: .none,
            availabilityStatus: .available,
            riskTier: .tier0ReadOnly,
            confirmationPolicy: .notRequired,
            executionKind: .readOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "MemoryCenterView.searchPreview", executor: "KairoMemoryBackendService.search"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.memory]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Memory store unavailable.", safeAlternative: "Answer without saved memory context."),
            sourceBinding: BuiltInPhoneToolSourceBinding(shortcutNodeKinds: [.searchMemory], recipeStepKinds: [.searchMemory])
        ),
        BuiltInPhoneToolDefinition(
            id: .memoryDelete,
            displayName: KairoL10n.string("memory.delete.accessibility"),
            category: .memory,
            schema: BuiltInPhoneToolSchema(input: "MemoryDeleteRequest", output: "MemoryDeleteResult"),
            permissionRequirement: .none,
            availabilityStatus: .available,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "MemoryCenterView.deletePreview", executor: "KairoMemoryBackendService.delete"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.memory]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Memory store unavailable.", safeAlternative: "Leave memory unchanged.")
        ),
        BuiltInPhoneToolDefinition(
            id: .memoryExport,
            displayName: KairoL10n.string("memory.export.accessibility"),
            category: .memory,
            schema: BuiltInPhoneToolSchema(input: "MemoryExportRequest", output: "MemoryExportFile"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewRequired,
            executionKind: .draftOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "MemoryCenterView.exportPreview", executor: "KairoMemoryBackendService.export"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.memory]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Memory export unavailable.", safeAlternative: "Show memory records in Memory Center.")
        ),
        BuiltInPhoneToolDefinition(
            id: .shareImport,
            displayName: KairoL10n.string("capability.shareExtension.title"),
            category: .share,
            schema: BuiltInPhoneToolSchema(input: "ShareExtensionPayload", output: "PendingSharedContent"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewRequired,
            executionKind: .draftOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ShareImportBanner", executor: "ShareIngestionQueue.enqueue"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.shareExtension]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Share queue unavailable.", safeAlternative: "Copy the content into Chat manually."),
            sourceBinding: BuiltInPhoneToolSourceBinding(shortcutNodeKinds: [.summarize, .extractTasks])
        ),
        BuiltInPhoneToolDefinition(
            id: .reminderWrite,
            displayName: KairoL10n.string("chat.action.displayName.createReminder"),
            category: .reminders,
            schema: BuiltInPhoneToolSchema(input: "ReminderDraft", output: "ConfirmedReminderResult"),
            permissionRequirement: .runtimePrompt,
            availabilityStatus: .permissionRequired,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.reminder", executor: "SandboxActionExecutor.createReminder"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.reminders]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Reminders permission denied or EventKit unavailable.", safeAlternative: "Show a reminder draft for manual copy."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.createReminderDraft], shortcutNodeKinds: [.createReminderDraft], recipeStepKinds: [.createReminderDraft])
        ),
        BuiltInPhoneToolDefinition(
            id: .calendarWrite,
            displayName: KairoL10n.string("chat.action.displayName.createCalendar"),
            category: .calendar,
            schema: BuiltInPhoneToolSchema(input: "CalendarEventDraft", output: "ConfirmedCalendarEventResult"),
            permissionRequirement: .runtimePrompt,
            availabilityStatus: .permissionRequired,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.calendar", executor: "SandboxActionExecutor.createCalendarEvent"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.calendar]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Calendar permission denied or EventKit unavailable.", safeAlternative: "Show a calendar draft for manual copy."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.createCalendarDraft], shortcutNodeKinds: [.createCalendarDraft], recipeStepKinds: [.createCalendarDraft])
        ),
        BuiltInPhoneToolDefinition(
            id: .notificationSchedule,
            displayName: KairoL10n.string("chat.action.displayName.sendNotification"),
            category: .notifications,
            schema: BuiltInPhoneToolSchema(input: "NotificationDraft", output: "ScheduledNotificationResult"),
            permissionRequirement: .runtimePrompt,
            availabilityStatus: .permissionRequired,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.notification", executor: "SandboxActionExecutor.scheduleNotification"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.notifications]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Notification permission denied.", safeAlternative: "Show the notification draft without scheduling."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.sendNotification], recipeStepKinds: [.sendLocalNotificationDraft])
        ),
        BuiltInPhoneToolDefinition(
            id: .contactCreate,
            displayName: KairoL10n.string("chat.action.displayName.createContact"),
            category: .contacts,
            schema: BuiltInPhoneToolSchema(input: "ContactDraft", output: "ConfirmedContactResult"),
            permissionRequirement: .runtimePrompt,
            availabilityStatus: .permissionRequired,
            riskTier: .tier2LowRiskWrite,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .confirmedWrite,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.contact", executor: "SandboxActionExecutor.createContact"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.contacts]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Contacts permission denied.", safeAlternative: "Show a contact draft for manual entry."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.createContactDraft], shortcutNodeKinds: [.createContactDraft])
        ),
        BuiltInPhoneToolDefinition(
            id: .emailHandoff,
            displayName: KairoL10n.string("chat.action.displayName.composeEmail"),
            category: .handoff,
            schema: BuiltInPhoneToolSchema(input: "EmailDraft", output: "VisibleMailtoHandoff"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .visibleHandoff,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.email", executor: "SandboxActionExecutor.openMailtoURL"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.mail]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Mail handoff URL could not be opened.", safeAlternative: "Show the email draft for manual copy."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.composeEmailDraft], shortcutNodeKinds: [.createEmailDraft, .draftReply])
        ),
        BuiltInPhoneToolDefinition(
            id: .messageHandoff,
            displayName: KairoL10n.string("chat.action.displayName.openMessages"),
            category: .handoff,
            schema: BuiltInPhoneToolSchema(input: "MessageDraft", output: "VisibleSMSHandoff"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .visibleHandoff,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.message", executor: "SandboxActionExecutor.openSMSURL"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.messages]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Messages handoff URL could not be opened.", safeAlternative: "Show the message draft for manual copy."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.openMessageHandoff], shortcutNodeKinds: [.prepareMessageHandoff])
        ),
        BuiltInPhoneToolDefinition(
            id: .phoneHandoff,
            displayName: KairoL10n.string("chat.action.displayName.openPhone"),
            category: .handoff,
            schema: BuiltInPhoneToolSchema(input: "PhoneCallDraft", output: "VisibleTelHandoff"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .visibleHandoff,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.phone", executor: "SandboxActionExecutor.openTelURL"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.phone]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Phone handoff URL could not be opened.", safeAlternative: "Show the phone number for manual dialing."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.openPhoneCallHandoff], shortcutNodeKinds: [.preparePhoneCallHandoff])
        ),
        BuiltInPhoneToolDefinition(
            id: .webSearchHandoff,
            displayName: KairoL10n.string("chat.action.displayName.openWeb"),
            category: .handoff,
            schema: BuiltInPhoneToolSchema(input: "WebSearchDraft", output: "VisibleHTTPSHandoff"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .visibleHandoff,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.webSearch", executor: "SandboxActionExecutor.openHTTPSURL"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.web]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Web handoff URL could not be opened.", safeAlternative: "Show the search URL for manual opening."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.openWebSearchHandoff], shortcutNodeKinds: [.prepareWebSearchHandoff])
        ),
        BuiltInPhoneToolDefinition(
            id: .mapsDirectionsHandoff,
            displayName: KairoL10n.string("chat.action.displayName.openMaps"),
            category: .handoff,
            schema: BuiltInPhoneToolSchema(input: "MapDirectionsDraft", output: "VisibleMapsHandoff"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .visibleHandoff,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.maps", executor: "SandboxActionExecutor.openMapsURL"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.location]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Maps handoff URL could not be opened.", safeAlternative: "Show the destination query for manual navigation."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.openMapDirections, .openURL])
        ),
        BuiltInPhoneToolDefinition(
            id: .recipeRun,
            displayName: KairoL10n.string("automations.recipe.run"),
            category: .recipe,
            schema: BuiltInPhoneToolSchema(input: "KairoRecipeRunRequest", output: "KairoRecipeRunPreviewOrResult"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewRequired,
            executionKind: .draftOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "AutomationsView.recipePreview", executor: "KairoRecipeRunner.runPreviewFirst"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.appIntents]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Recipe runner unavailable.", safeAlternative: "Show recipe steps without running them."),
            sourceBinding: BuiltInPhoneToolSourceBinding(shortcutNodeKinds: [.dailyBriefing, .createRecipeDraft], recipeStepKinds: [.askKairo, .summarizeText, .extractTasks, .enqueueActionDraft, .noOp])
        ),
        BuiltInPhoneToolDefinition(
            id: .shortcutNodeInvocation,
            displayName: KairoL10n.string("root.section.shortcuts.title"),
            category: .shortcuts,
            schema: BuiltInPhoneToolSchema(input: "ShortcutNodeInput", output: "ShortcutNodeOutput"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .available,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewRequired,
            executionKind: .draftOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "SettingsShortcutDemosSection.preview", executor: "ShortcutNodeInvocationService.invoke"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.appIntents]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Shortcut node runtime unavailable.", safeAlternative: "Show node input/output schema only."),
            sourceBinding: BuiltInPhoneToolSourceBinding(shortcutNodeKinds: [.ask])
        ),
        BuiltInPhoneToolDefinition(
            id: .oauthConnectorSetupStatus,
            displayName: KairoL10n.string("capability.externalConnectors.title"),
            category: .integrations,
            schema: BuiltInPhoneToolSchema(input: "OAuthConnectorSetupRequest", output: "OAuthConnectorStatus"),
            permissionRequirement: .oauth,
            availabilityStatus: .setupRequired,
            riskTier: .tier0ReadOnly,
            confirmationPolicy: .manualSetupOnly,
            executionKind: .setupStatusOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "SettingsOAuthConnectorsSection.status", executor: "OAuthConnectorLoginCenter.statusOnly"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.externalConnectors]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "OAuth connector is not configured.", safeAlternative: "Open Settings to connect an account."),
            sourceBinding: BuiltInPhoneToolSourceBinding(skillKinds: [.oauthConnector])
        ),
        BuiltInPhoneToolDefinition(
            id: .localModelManage,
            displayName: KairoL10n.string("settings.models.section"),
            category: .localModels,
            schema: BuiltInPhoneToolSchema(input: "LocalModelManagementRequest", output: "LocalModelSettingsStatus"),
            permissionRequirement: .userInitiated,
            availabilityStatus: .setupRequired,
            riskTier: .tier1Draft,
            confirmationPolicy: .previewRequired,
            executionKind: .draftOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "LocalModelsCompactView", executor: "LocalModelSettingsService.catalogDownloadSelectDelete"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.chat]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Local model service unavailable.", safeAlternative: "Use cloud route or local-only unavailable copy."),
            sourceBinding: BuiltInPhoneToolSourceBinding(skillKinds: [.localModel])
        ),
        BuiltInPhoneToolDefinition(
            id: .homeKitPreview,
            displayName: KairoL10n.string("chat.action.displayName.controlHome"),
            category: .home,
            schema: BuiltInPhoneToolSchema(input: "HomeControlRequest", output: "HomeControlPreview"),
            permissionRequirement: .runtimePrompt,
            availabilityStatus: .scaffolded,
            riskTier: .tier3HighRiskExternal,
            confirmationPolicy: .previewAndExplicitConfirmation,
            executionKind: .scaffoldPreviewOnly,
            lifecycle: BuiltInPhoneToolLifecycleBinding(previewRenderer: "ActionPreviewView.homeControl", executor: "SandboxActionExecutor.homeKitPreviewOnly"),
            audit: BuiltInPhoneToolAuditMetadata(capabilityKeys: [.homeKit]),
            fallback: BuiltInPhoneToolFallback(unsupportedReason: "Real HomeKit entitlement/control is not enabled.", safeAlternative: "Show a preview-only HomeKit scaffold."),
            sourceBinding: BuiltInPhoneToolSourceBinding(agentActionKinds: [.controlHome], shortcutNodeKinds: [.previewHomeAction], recipeStepKinds: [.readHomeState, .proposeHomeAction], skillKinds: [.homeKitControl])
        )
    ]
}
